apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: c11
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c11 
  name: c11
  namespace: refactor
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: c11
    weight: 100 

