apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c12
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: argocd/application
    repoURL: https://github.com/jduimovich/refactor
    targetRevision: main
  destination:
    namespace: refactor
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

